import { ARCMetaCollectionMap, ARCMetaModel, ARCModel } from "../types/model.types";
import { ARCConfig } from "../types/config.types";
import { AnyProps } from "../types/components.types";
export declare function flatten<Model>(arcCollectionMap: ARCMetaCollectionMap<Model>, withMetas?: boolean): ARCModel<Model>[] | ARCMetaModel<Model>[];
export declare function extendWithDefaultProps<Model, RequiredProps = {}, P = {}>(config: ARCConfig<Model, RequiredProps>, ownProps: P): AnyProps;
export type ObjectValues<T> = T[keyof T];
export declare function extractParams(props?: string[], source?: AnyProps): {};
export declare function getParams<Model, RequiredProps = {}>(config: ARCConfig<Model, RequiredProps>, source?: RequiredProps): RequiredProps;
export declare const changedProps: (prevProps: AnyProps, nextProps: AnyProps) => string[];
export declare function cleanParams(str: string): string;
export declare function stringIsReplaceable(str: string): boolean;
export declare function interpolate(str: string | null, params: object): string;
export declare function getDefaultConfig<Model, RequiredProps>(): ARCConfig<Model, RequiredProps>;
export declare function omit<T extends object, K extends keyof T>(obj: T, keysToOmit?: K | K[]): Omit<T, K>;
export declare function initializeConfig<Model, RequiredProps>(config: ARCConfig<Model, RequiredProps>): ARCConfig<Model, RequiredProps>;
